### ISSUE TITLE
Limitation : Related records filtering not honoured

### ISSUE THREAD

**Issue by drivardxrm** [drivardxrm/LookupDropdown.PCF#1]
Currently, the records from the default view defined in the field properties of the form are displayed in the dropdown.

It would be nice to add the 'Related Records Filtering' as well.
![image](https://user-images.githubusercontent.com/38399134/147583585-c69cdf2b-cebd-427c-ac6e-6181d7d63413.png)

At the time of the first release, I wasn't able to figure out how to do so.

**Comment by tchinnin** [comment]
It would be even greater if we could pass fetchXML to perform complex filtering, instead of the limited "Related Records Filtering" feature.

**Comment by drivardxrm** [comment]
added in v1.0.0.3
