### ISSUE TITLE
Deactivate/Activate status for values

### ISSUE THREAD

**Issue by ChloeM17** [drivardxrm/LookupDropdown.PCF#12]
Good afternoon David, 

Thank you for this amazing PCF. 
I have installed the PCF and I encounter a functional problem on the Activate/Deactivate part. 

I made an example, I would like to deactivate the country Switzerland (could not be selected for user but still remains as a data in my application). 
If I change the filter on the lookup and set the Status to all (the dropdown will show all the data in the countries and my data will remain on the form).
![Lookup all status](https://user-images.githubusercontent.com/108683428/177188463-6642e868-ed3e-4994-b121-5063d5ecef3f.png)

But if I change the view to only select the Active countries, the field be emptied and no data will be show. 
If I reactive the country, the field still remains empty (auto save on on the environment). 
![Lookup active status only - field empty](https://user-images.githubusercontent.com/108683428/177188459-b5a44285-7cf1-4488-9ce1-bc565139bc14.png)
![Lookup active status only](https://user-images.githubusercontent.com/108683428/177188462-860da9e2-4b22-48c3-926b-56e27b665fc4.png)

Maybe I miss something. Could you help me on that matter? 

Thank you very much for your work and helping the community :)

**Comment by drivardxrm** [comment]
Hi @ChloeM17 ,
Thanks for your interest in the control ;)

That is an interesting use case.
I'm not sure if I can do something about it but I will give it a try.

I will try to add a parameter to the control : ex.   'Keep existing unlisted value'   (Yes/No)

Now if this param is set to YES,
The value should be kept and displayed in the field (maybe grayed out)

I will keep you posted and maybe send you an early version for you to test.

**Comment by ChloeM17** [comment]
Hello @drivardxrm ! 

Thanks a lot for your reply and take the time to look at it :)

Sure do not hesitate to send me a version to test.

**Comment by drivardxrm** [comment]
Hi @ChloeM17 ,
I fixed the issue in the latest version of the control v1.0.0.8
https://github.com/drivardxrm/LookupDropdown.PCF/releases/tag/v1.0.0.8

Thanks ;)

**Comment by ChloeM17** [comment]
Hi @drivardxrm, 
Thank you very much for fixing the issue :)

I wish you a nice summer :)
