### ISSUE TITLE
PCF stop working when filters are added to custom view

### ISSUE THREAD

**Issue by Quentin-L21** [drivardxrm/LookupDropdown.PCF#2]
Hi !

I've the following issue regarding the PCF when using a custom view with filters : 
![CustomView](https://user-images.githubusercontent.com/69462335/150115272-d085cd54-7199-40d1-8417-4bcd277facf7.gif)

But when I'm using a default view it works without problems.

Can you take a look ?

Thank you !

Kind regards.

**Comment by drivardxrm** [comment]
Hi @Quentin-L21 
Thanks for the feedback, I will have a look.

Can you show me an example of your custom view fetch xml ? so I can reproduce in my environment.

**Comment by Quentin-L21** [comment]
Hi @drivardxrm , 
Thanks for your quick feedback.

Here is the fetch xml I'm using (sorry if some words are in French) : 
`<fetch version="1.0" mapping="logical" distinct="true">
  <entity name="bookingstatus">
    <attribute name="bookingstatusid" />
    <attribute name="name" />
    <attribute name="msdyn_fieldservicestatus" />
    <filter type="and">
      <condition attribute="statecode" operator="eq" value="0" />
      <condition attribute="msdyn_fieldservicestatus" operator="not-null" />
      <filter type="and">
        <condition attribute="name" operator="ne" value="Pré-Planifié" />
        <condition attribute="name" operator="ne" value="Validé" />
        <condition attribute="name" operator="ne" value="En déplacement" />
        <condition attribute="name" operator="ne" value="Annulé" />
      </filter>
    </filter>
  </entity>
</fetch>`

**Comment by drivardxrm** [comment]
@Quentin-L21 pas de problèmes, je suis francophone ;)

Je regarde tout ça dès que possible.

**Comment by drivardxrm** [comment]
Hi @Quentin-L21 ,

Can you try the latest release v1.0.0.2, the bug should be corrected,
Please tell me if it works well in your hands.
https://github.com/drivardxrm/LookupDropdown.PCF/releases/tag/v1.0.0.2

Thanks for the catch!

**Comment by Quentin-L21** [comment]
Hi @drivardxrm ,

I just tested it and it works perfectly as expected.

Keep up the good work ! 👍 

Merci pour ta rapidité de résolution ;)
