### ISSUE TITLE
Error fetching data...

### ISSUE THREAD

**Issue by tomsaudrins** [drivardxrm/LookupDropdown.PCF#6]
Hi,
We have three lookup fields,
The business unit, country and location.

Available countries depend on the business unit selected, and location depends on the country selected.
for the location field, the dependent lookup works perfectly. 

For the country field, however, it attempts to load, and then proceeds to display "error fetching data"
![image](https://user-images.githubusercontent.com/67427155/158425567-f5e20466-02d9-44d4-a640-d0a26754aa0d.png)

Issue here is that the business unit has M:M relationship.
In default settings, filtering is accomplished with if business unit contains country,
Is this something I can also do with this PCF?

Thank you!

**Comment by drivardxrm** [comment]
Hi @tomsaudrins,
Thanks for reporting the issue. 
I will try to reproduce on my side and come up with a fix.

**Comment by drivardxrm** [comment]
Hi @tomsaudrins 
I have released a new version that fixes this issue v1.0.0.5 
https://github.com/drivardxrm/LookupDropdown.PCF/releases/tag/v1.0.0.5

Please tell me if it works well in your hands.

Again, thanks for raising the issue

**Comment by tomsaudrins** [comment]
Hi @drivardxrm,

Tested the N:N fields and it works without any issues now!
Only problem now, is that the "location" field that depends on "country" which depends N : N "business unit" does not work.

So select business unit - works fine
Select country - works fine
Select location (depending on country, location can have only one country). - works until country is selected, then error fetching data.

Could this be related to the recent changes you made, or should I look into something from my side?

![image](https://user-images.githubusercontent.com/67427155/158754812-f20e2001-0643-4507-bb8e-3fb875dbf846.png)

**Comment by drivardxrm** [comment]
Hi @tomsaudrins 
Can you try the latest version v1.0.0.6
I introduced a regression with the 1.0.0.5 fix

Tell me if it works now

**Comment by tomsaudrins** [comment]
Will perform more throughout testing tomorrow, but I checked the form and it seems that it works flawlessly.
Thank you so much! :)

**Comment by drivardxrm** [comment]
Great!
